# netlify.toml
[build]
  command = "npm install && npm run build"
  publish = "dist/qa-portfolio-angular/browser"
  framework = "#static"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
