[build]
  command = "npm install && npm run build"
  publish = "dist/portfolio/browser"
  framework = "#static"

[build.environment]
  NODE_VERSION = "22.18.0"   # Or any Node version your Angular build supports

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
